      
  - name: Print IP Address
    shell:  echo JWT
    register: print_result

  #show the output on the user/us Cli
  - name: print message
    debug:
      msg: "{{ print_result.stdout_lines }}"

  - name: "Install Kubectl"
    shell: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl  /usr/local/bin/
        kubectl version --client -o json

  - name: "Install Docker"
    shell: |
        #sudo apt install docker.io
        #sudo apt-get install -y docker.io
        sudo apt-get update && sudo apt-get install docker.io -y
    
  - name: "Install Minikube"
    shell: |
        wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube-linux-amd64
        sudo mv minikube-linux-amd64 /usr/local/bin/minikube
        minikube version

  - name: "Add user Minikube"
    shell: |   
        sudo groupadd docker
        sudo gpasswd -a $USER docker
        #sudo usermod -aG docker $USER && newgrp docker
        #getent group
        
  - name: "Start Minikube"
    shell: |        
        minikube start --driver=docker

  - name: "Kubernetes Run"
    shell: |
        docker pull jiewwantan/cloud_devops:latest      
        kubectl run devops-capstone-deployment --image=jiewwantan/cloud_devops --port=80 --labels app=devops-capstone-deployment
        #kubectl create deployment devops-capstone-deployment2 --image=jiewwantan/cloud_devops 
        
  - name: "wait 20 seconds for target connection to become reachable/usable."
    wait_for_connection: 
        delay: 30
      
  - name: "Kubernetes Port forwward"
    shell: |
        nohup kubectl port-forward devops-capstone-deployment 8000:80 --address='0.0.0.0' --pod-running-timeout=15m0s &
        echo -ne '\n' | "nohup applied"
        #cat nohup.out
    register: print_result

  - name: print message
    debug:
      msg: "{{ print_result.stdout_lines }}"
      
  - name: "wait 60 seconds for target connection to become reachable/usable."
    wait_for_connection: 
        delay: 60